"""add portfolio sections

Revision ID: b725bf9dbfdc
Revises: 4930cd94b8f9
Create Date: 2026-08-14 00:03:02.370221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b725bf9dbfdc'
down_revision: Union[str, None] = '4930cd94b8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_sections_id'), 'portfolio_sections', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_section_type'), 'portfolio_sections', ['section_type'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_studio_id'), 'portfolio_sections', ['studio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_sections_studio_id'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_section_type'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_id'), table_name='portfolio_sections')
    op.drop_table('portfolio_sections')
    # ### end Alembic commands ###
