/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlbumEditorRouteImport } from './routes/album-editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardMediaRouteImport } from './routes/dashboard.media'
import { Route as DashboardCustomizeRouteImport } from './routes/dashboard.customize'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard.builder'
import { Route as DashboardBrandRouteImport } from './routes/dashboard.brand'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardAlbumsIndexRouteImport } from './routes/dashboard.albums.index'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardAlbumsNewRouteImport } from './routes/dashboard.albums.new'
import { Route as DashboardAlbumsIdRouteImport } from './routes/dashboard.albums.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumEditorRoute = AlbumEditorRouteImport.update({
  id: '/album-editor',
  path: '/album-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/studio/$slug',
  path: '/studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomizeRoute = DashboardCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandRoute = DashboardBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlbumsIndexRoute = DashboardAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlbumsNewRoute = DashboardAlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlbumsIdRoute = DashboardAlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album-editor': typeof AlbumEditorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/customize': typeof DashboardCustomizeRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/event/$slug': typeof EventSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/albums/$id': typeof DashboardAlbumsIdRoute
  '/dashboard/albums/new': typeof DashboardAlbumsNewRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/albums/': typeof DashboardAlbumsIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album-editor': typeof AlbumEditorRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/customize': typeof DashboardCustomizeRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/event/$slug': typeof EventSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/albums/$id': typeof DashboardAlbumsIdRoute
  '/dashboard/albums/new': typeof DashboardAlbumsNewRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/albums': typeof DashboardAlbumsIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album-editor': typeof AlbumEditorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/brand': typeof DashboardBrandRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/customize': typeof DashboardCustomizeRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/event/$slug': typeof EventSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/albums/$id': typeof DashboardAlbumsIdRoute
  '/dashboard/albums/new': typeof DashboardAlbumsNewRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/albums/': typeof DashboardAlbumsIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album-editor'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/dashboard/analytics'
    | '/dashboard/brand'
    | '/dashboard/builder'
    | '/dashboard/content'
    | '/dashboard/create'
    | '/dashboard/customize'
    | '/dashboard/media'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/event/$slug'
    | '/studio/$slug'
    | '/dashboard/'
    | '/dashboard/albums/$id'
    | '/dashboard/albums/new'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/albums/'
    | '/dashboard/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album-editor'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/dashboard/analytics'
    | '/dashboard/brand'
    | '/dashboard/builder'
    | '/dashboard/content'
    | '/dashboard/create'
    | '/dashboard/customize'
    | '/dashboard/media'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/event/$slug'
    | '/studio/$slug'
    | '/dashboard'
    | '/dashboard/albums/$id'
    | '/dashboard/albums/new'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/albums'
    | '/dashboard/events'
  id:
    | '__root__'
    | '/'
    | '/album-editor'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/register'
    | '/templates'
    | '/dashboard/analytics'
    | '/dashboard/brand'
    | '/dashboard/builder'
    | '/dashboard/content'
    | '/dashboard/create'
    | '/dashboard/customize'
    | '/dashboard/media'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/event/$slug'
    | '/studio/$slug'
    | '/dashboard/'
    | '/dashboard/albums/$id'
    | '/dashboard/albums/new'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/albums/'
    | '/dashboard/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumEditorRoute: typeof AlbumEditorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  TemplatesRoute: typeof TemplatesRoute
  EventSlugRoute: typeof EventSlugRoute
  StudioSlugRoute: typeof StudioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album-editor': {
      id: '/album-editor'
      path: '/album-editor'
      fullPath: '/album-editor'
      preLoaderRoute: typeof AlbumEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/studio/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customize': {
      id: '/dashboard/customize'
      path: '/customize'
      fullPath: '/dashboard/customize'
      preLoaderRoute: typeof DashboardCustomizeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand': {
      id: '/dashboard/brand'
      path: '/brand'
      fullPath: '/dashboard/brand'
      preLoaderRoute: typeof DashboardBrandRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/albums/': {
      id: '/dashboard/albums/'
      path: '/albums'
      fullPath: '/dashboard/albums/'
      preLoaderRoute: typeof DashboardAlbumsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/albums/new': {
      id: '/dashboard/albums/new'
      path: '/albums/new'
      fullPath: '/dashboard/albums/new'
      preLoaderRoute: typeof DashboardAlbumsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/albums/$id': {
      id: '/dashboard/albums/$id'
      path: '/albums/$id'
      fullPath: '/dashboard/albums/$id'
      preLoaderRoute: typeof DashboardAlbumsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBrandRoute: typeof DashboardBrandRoute
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardCustomizeRoute: typeof DashboardCustomizeRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAlbumsIdRoute: typeof DashboardAlbumsIdRoute
  DashboardAlbumsNewRoute: typeof DashboardAlbumsNewRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardAlbumsIndexRoute: typeof DashboardAlbumsIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBrandRoute: DashboardBrandRoute,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardCustomizeRoute: DashboardCustomizeRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAlbumsIdRoute: DashboardAlbumsIdRoute,
  DashboardAlbumsNewRoute: DashboardAlbumsNewRoute,
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardAlbumsIndexRoute: DashboardAlbumsIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumEditorRoute: AlbumEditorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  TemplatesRoute: TemplatesRoute,
  EventSlugRoute: EventSlugRoute,
  StudioSlugRoute: StudioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
